### ISSUE TITLE
Using hiera_data_hash causes puppet stack trace

### ISSUE THREAD

**Issue by v1peractual** [southalc/vault#4]
When I attempt to retrieve secrets from vault, I get the following:

```
[root@dt-conf01 vault]# puppet lookup --environment production --verbose --trace profile_dns_cache::search_domain
s
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Warning: Undefined variable 'site';
   (file & line not available)
Warning: Undefined variable 'cluster';
   (file & line not available)
Warning: Undefined variable 'role';
   (file & line not available)
Error: Could not run: undefined method `scrub' for nil:NilClass
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/error.rb:6:in `initialize'
/etc/puppetlabs/code/environments/production/modules/vault_secrets/lib/puppet/shared/vault_common.rb:35:in `exception'
/etc/puppetlabs/code/environments/production/modules/vault_secrets/lib/puppet/shared/vault_common.rb:35:in `raise'
/etc/puppetlabs/code/environments/production/modules/vault_secrets/lib/puppet/shared/vault_common.rb:35:in `vault_http_get'
/etc/puppetlabs/code/environments/production/modules/vault_secrets/lib/puppet/functions/vault_hiera_hash.rb:57:in `vault_hiera_hash'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatch.rb:60:in `invoke'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatcher.rb:43:in `block in dispatch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatcher.rb:42:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatcher.rb:42:in `dispatch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/function.rb:46:in `block in call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/function.rb:45:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/function.rb:45:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:77:in `call_data_hash_function'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:70:in `data_hash'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:55:in `data_value'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:51:in `lookup_key'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:41:in `block in invoke_with_location'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:136:in `with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:39:in `invoke_with_location'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:28:in `block (2 levels) in unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:126:in `lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:27:in `block in unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:136:in `with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_hash_function_provider.rb:26:in `unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/configured_data_provider.rb:56:in `block (2 levels) in unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:132:in `block (3 levels) in lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:131:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:131:in `block (2 levels) in lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:129:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:129:in `reduce'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:129:in `block in lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:136:in `with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/merge_strategy.rb:128:in `lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/configured_data_provider.rb:55:in `block in unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:136:in `with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/configured_data_provider.rb:48:in `unchecked_key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_provider.rb:26:in `block in key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:97:in `check'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/data_provider.rb:26:in `key_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:157:in `lookup_in_environment'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:384:in `block in env_lookup_opti
ons'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:384:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:384:in `env_lookup_options'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:348:in `block (2 levels) in retrieve_lookup_options'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:136:in `with'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:344:in `block in retrieve_lookup_options'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:82:in `lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:343:in `retrieve_lookup_options'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:237:in `lookup_lookup_options'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:64:in `block in lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/invocation.rb:82:in `lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup/lookup_adapter.rb:59:in `lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:76:in `search_and_merge'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:31:in `block (2 levels) in lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:31:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:31:in `block in lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:29:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:29:in `reduce'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:29:in `lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/lookup.rb:322:in `block in main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/lookup.rb:378:in `block in generate_scope'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:153:in `block in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:302:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:123:in `compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/lookup.rb:378:in `generate_scope'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/lookup.rb:318:in `main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:437:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:421:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:744:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:421:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:143:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:77:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
```
I am running 
```
[root@dt-conf01 ~]# puppet --version
7.11.0

```
I have tried both PKI cert and using a token and they both result in the same issue.

If the authentication is incorrect or the path is incorrect, the error is a standard error.

hiera.yaml:
```
  - name: "Secrets from Vault"
    data_hash: "vault_hiera_hash"
    uris:
      - "https://asd-vault1.internal.ncsa.edu:8202/v1/delta/"
    options:
      timeout: 3
      token_file: "/etc/puppetlabs/puppet/vault/delta-vault-token"
      ca_trust: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"

```

**Comment by southalc** [comment]
Please try to update line 108 in the 'append_api_errors' method of file "lib/puppet/shared/vault_common.rb" file from nil to 'unknown' and re-try the lookup.  You may need to restart the puppetserver process after changing the file.  I believe the lookup will still fail, but it should not crash puppet.  Here's what the updated method should look like:
```
def append_api_errors(message, response)
  # @summary Add meaningful(?) messages to errors
  errors = begin
             JSON.parse(response.body)['errors']
           rescue StandardError
             'unknown'
           end
  message << " (api errors: #{errors})" if errors
end
```
Let me know if this prevents Puppet from crashing.  If so, I'll make the change to the module and post an updated version.

Just for curiosity, could you also separately test a lookup by changing the URL to remove the trailing slash?  I tested on my own system here and get a 404 error when the trailing slash in on the URL, although it does not crash my puppet lookup. Thanks

**Comment by v1peractual** [comment]
I did that (changed line 108 and restarted) and it didn't fix it. I modified the URL and that didn't fix it either) I added a version to the options as I realized I was using kv2. That didn't help.

```
Error: Could not run: undefined method `scrub' for nil:NilClass
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/error.rb:6:in `initialize'
/etc/puppetlabs/code/environments/production/modules/vault_secrets/lib/puppet/shared/vault_common.rb:35:in `exception'
/etc/puppetlabs/code/environments/production/modules/vault_secrets/lib/puppet/shared/vault_common.rb:35:in `raise'
/etc/puppetlabs/code/environments/production/modules/vault_secrets/lib/puppet/shared/vault_common.rb:35:in `vault_http_get'
/etc/puppetlabs/code/environments/production/modules/vault_secrets/lib/puppet/functions/vault_hiera_hash.rb:57:in `vault_hiera_hash'
```

```
  - name: "Secrets from Vault"
    data_hash: "vault_hiera_hash"
    uris:
      - "https://asd-vault1.internal.ncsa.edu:8202/v1/delta/krb5"
    options:
      timeout: 3
      version: "v2"
      token_file: "/etc/puppetlabs/puppet/vault/delta-vault-token"
      ca_trust: "/etc/puppetlabs/puppet/ssl/certs/ca.pem"
```

**Comment by v1peractual** [comment]
Alright, my apologies for the issues, but I working through it. I think the output from the curl is causing the error.

```
[root@dt-conf01 ~]# curl -k --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/delta/
{"request_id":"fad9fe42-157b-2034-d1e7-26fe2808dfdb","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get' for this operation."],"auth":null}[root@dt-conf01 ~]# curl -k --header "X-Vault-Token: $VAULT_TOKEN" $VAULT_ADDR/v1/delta/krb5
```
My guess if the error handling isn't taking this into consideration.

I have fixed the path. I guess you need data after the secret path for versioned secrets.

I now get this:

  ```
Hierarchy entry "Secrets from Vault"
        URI "https://asd-vault1.internal.ncsa.edu:8202/v1/delta/data/krb5"
          Original uri: "https://asd-vault1.internal.ncsa.edu:8202/v1/delta/data/krb5"
Unable to find 'data_hash' function named 'hiera_data_hash' (file: /etc/puppetlabs/code/environments/production/hiera.yaml)
```
I do appreciate any help.

**Comment by southalc** [comment]
The curl output was helpful.  I was able to reproduce the issue on my system as follows:
- Created a v2 secrets engine mounted on "puppet2/"
- Created a secret named "test" under "puppet2/" and added a key/value pair "secret1"/"don't tell"
- Configured hiera.yaml as follows:
```
  - name: "Secrets from Vault"
    data_hash: vault_hiera_hash
    uris:
      - "https://vault.southall.local:8200/v1/puppet2/test"
    options:
      timeout: 2
      token_file: "/run/puppet/vault-token"
      ca_trust: "/etc/ssl/certs/southall.pem"
      version: "v2"
```
Result of the lookup:
```
# puppet lookup --environment test secret1
Error: Could not run: undefined method `scrub' for nil:NilClass
```
I was able to complete a successful lookup by inserting "data" in between the secrets engine and secret name per the following full example, which it looks like you've already done from your last post:
```
hierarchy:
  - name: "Secrets from Vault"
    data_hash: vault_hiera_hash
    uris:
      - "https://vault.southall.local:8200/v1/puppet2/data/test"
    options:
      timeout: 2
      token_file: "/run/puppet/vault-token"
      ca_trust: "/etc/ssl/certs/southall.pem"
      version: "v2"
```
And here's the result of the lookup:
```
# puppet lookup --environment test secret1
--- don't tell
```

I will attempt to fix the error handling on this type of response with a v2 failure, but it appears to work when the configuration is correct.  That last lookup failure you posted was a for a value of "vault_hiera_hash"?  Can you verify the contents of your v2 secrets using curl and then try puppet lookup on a key that is confirmed to be present?  You should be able to lookup any key present in the secret.
```
curl -k --header "X-Vault-Token: $VAULT_TOKEN" "$VAULT_ADDR/v1/delta/data/krb5"
```

**Comment by southalc** [comment]
I created the "refactor_shared_functions" branch that addresses this issue.  Hiera lookups against an invalid Vault path will now return not found.  I have a little more work to do before this will get merged back to the master branch, but I believe it's all in a functional state.

**Comment by southalc** [comment]
closed with version 0.3.1
